title: Sapphire
description: Documentation for the Sapphire programming language

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

enable_copy_code_button: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
