title: Sapphire
description: Documentation for the Sapphire programming language

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.17.2"

aux_links:
  "GitHub":
    - "//github.com/zziccardi/sapphire"

back_to_top: true
back_to_top_text: "Back to top"
