"""Visitor implementation for building Sapphire AST from ANTLR parse tree.

This module walks the parse tree generated by the ANTLR parser and constructs
a strongly typed abstract syntax tree (AST) using the node classes defined in
ast.py.
"""

from typing import List

from src.parser.ast import *
from src.parser.gen.SapphireVisitor import SapphireVisitor
from src.parser.gen.SapphireParser import SapphireParser




class ASTBuilder(SapphireVisitor):
  """Walks the ANTLR Parse Tree and constructs a Sapphire AST."""

  def visit(self, tree):
    # This override is only needed for the language server to track token locations.
    # It does not affect compilation/transpilation.
    node = super().visit(tree)
    if isinstance(node, ASTNode) and tree is not None:
      if hasattr(tree, "start") and tree.start is not None:
        node.start_line = tree.start.line
        node.start_column = tree.start.column
        if hasattr(tree, "stop") and tree.stop is not None:
          node.end_line = tree.stop.line
          node.end_column = tree.stop.column + len(tree.stop.text)
          if node.start_line == node.end_line:
            node.length = node.end_column - node.start_column
    return node

  def visitProgram(self, ctx: SapphireParser.ProgramContext) -> ProgramNode:
    declarations = []
    imports = []
    export_block = None
    for item in ctx.topLevelItem():
      node = self.visit(item)
      if isinstance(node, ImportStmtNode):
        imports.append(node)
      elif isinstance(node, ExportStmtNode):
        if export_block is not None:
          raise SyntaxError("Only a single export block is allowed per file.")
        export_block = node
      elif node is not None:
        declarations.append(node)
    return ProgramNode(declarations, imports=imports, export_block=export_block)

  def visitTopLevelItem(self, ctx: SapphireParser.TopLevelItemContext) -> Optional[ASTNode]:
    if ctx and ctx.children:
      return self.visit(ctx.getChild(0))
    return None

  def visitImportStatement(self, ctx: SapphireParser.ImportStatementContext) -> ImportStmtNode:
    path = ctx.identifierPath().getText()
    alias = ctx.IDENTIFIER().getText() if ctx.IDENTIFIER() else None
    node = ImportStmtNode(path=path, alias=alias)
    if ctx.identifierPath():
      token = ctx.identifierPath().start
      node.path_line = token.line
      node.path_column = token.column
      node.path_length = len(ctx.identifierPath().getText())
    return node

  def visitExportStatement(self, ctx: SapphireParser.ExportStatementContext) -> ExportStmtNode:
    specifiers = [self.visit(spec) for spec in ctx.exportSpecifier()]
    return ExportStmtNode(specifiers=specifiers)

  def visitExportSpecifier(self, ctx: SapphireParser.ExportSpecifierContext) -> ExportSpecifierNode:
    has_dot = ctx.DOT() is not None
    has_as = ctx.AS() is not None
    identifiers = ctx.IDENTIFIER()

    module_prefix = None
    symbol = ""
    alias = None

    if has_dot:
      module_prefix = identifiers[0].getText()
      symbol = identifiers[1].getText() if len(identifiers) > 1 else ""
      if has_as and len(identifiers) > 2:
        alias = identifiers[2].getText()
    else:
      symbol = identifiers[0].getText() if identifiers else ""
      if has_as and len(identifiers) > 1:
        alias = identifiers[1].getText()

    return ExportSpecifierNode(symbol=symbol, module_prefix=module_prefix, alias=alias)

  def visitDeclaration(self, ctx: SapphireParser.DeclarationContext) -> DeclNode:
    return self.visit(ctx.getChild(0))

  def visitAnnotation(self, ctx: SapphireParser.AnnotationContext) -> AnnotationNode:
    name_token = ctx.IDENTIFIER() or ctx.EXPORT() or ctx.IMPORT()
    name = name_token.getText()
    arg = ctx.STRING_LIT().getText()[1:-1] if ctx.STRING_LIT() else None
    node = AnnotationNode(name, arg)
    token = name_token.getSymbol()
    at_token = ctx.AT().getSymbol()
    node.at_line = at_token.line
    node.at_column = at_token.column
    node.line = token.line
    node.column = token.column
    node.length = len(token.text)
    node.start_line = at_token.line
    node.start_column = at_token.column
    node.end_line = token.line
    node.end_column = token.column + len(token.text)
    if ctx.RPAREN():
      rparen = ctx.RPAREN().getSymbol()
      node.end_line = rparen.line
      node.end_column = rparen.column + 1
    return node

  def visitTypeParamList(self, ctx: SapphireParser.TypeParamListContext) -> List[str]:
    return [id_token.getText() for id_token in ctx.IDENTIFIER()]

  def visitTypeArgumentList(self, ctx: SapphireParser.TypeArgumentListContext) -> List[TypeNode]:
    return [self.visit(t) for t in ctx.type_()]

  def visitStructDeclaration(self, ctx: SapphireParser.StructDeclarationContext) -> StructDeclNode:
    name = ctx.IDENTIFIER(0).getText()
    parent_tokens = ctx.IDENTIFIER()[1:] if len(ctx.IDENTIFIER()) > 1 else []
    parent_names = [t.getText() for t in parent_tokens]
    type_params = self.visitTypeParamList(ctx.typeParamList()) if ctx.typeParamList() else []
    fields = [self.visit(field) for field in ctx.structField()] if ctx.structField() else []
    is_prototype = ctx.PROTO_KEYWORD() is not None
    node = StructDeclNode(name, parent_names, fields, is_prototype, type_params=type_params)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER(0).getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    node.parent_names_info = []
    for pt in parent_tokens:
      sym = pt.getSymbol()
      node.parent_names_info.append({
          "name": sym.text,
          "line": sym.line,
          "column": sym.column,
          "length": len(sym.text),
      })
    if parent_tokens:
      first_sym = parent_tokens[0].getSymbol()
      node.parent_name_line = first_sym.line
      node.parent_name_column = first_sym.column
      node.parent_name_length = len(first_sym.text)
    return node

  def visitEnumDeclaration(self, ctx: SapphireParser.EnumDeclarationContext) -> EnumDeclNode:
    name = ctx.IDENTIFIER().getText()
    members = [self.visit(member) for member in ctx.enumMember()]
    node = EnumDeclNode(name, members)
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitEnumMember(self, ctx: SapphireParser.EnumMemberContext) -> EnumMemberNode:
    name = ctx.IDENTIFIER().getText()
    val = None
    if ctx.INT_LIT():
      val = int(ctx.INT_LIT().getText())
    elif ctx.STRING_LIT():
      raw_str = ctx.STRING_LIT().getText()
      val = raw_str[1:-1]
    node = EnumMemberNode(name, val)
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitStructField(self, ctx: SapphireParser.StructFieldContext) -> StructFieldNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    field_type = self.visit(ctx.type_()) if ctx.type_() else None
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    node = StructFieldNode(is_mutable, name, field_type, default_expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitImplBlock(self, ctx: SapphireParser.ImplBlockContext) -> ImplBlockNode:
    trait_name = None
    if getattr(ctx, "traitName", None):
      tn = ctx.traitName
      trait_name = tn.getText() if hasattr(tn, "getText") else getattr(tn, "text", str(tn))
    sn = ctx.structName
    struct_name = sn.getText() if hasattr(sn, "getText") else getattr(sn, "text", str(sn))
    tpl = ctx.typeParamList()
    if tpl:
      type_params = self.visitTypeParamList(tpl[0] if isinstance(tpl, list) else tpl)
    else:
      type_params = []

    type_args_list = ctx.typeArgumentList()
    trait_type_args = []
    struct_type_args = []
    if ctx.traitName and ctx.FOR():
      if len(type_args_list) == 2:
        trait_type_args = self.visitTypeArgumentList(type_args_list[0])
        struct_type_args = self.visitTypeArgumentList(type_args_list[1])
      elif len(type_args_list) == 1:
        for_start = ctx.FOR().getSymbol().tokenIndex
        arg_start = type_args_list[0].start.tokenIndex
        if arg_start < for_start:
          trait_type_args = self.visitTypeArgumentList(type_args_list[0])
        else:
          struct_type_args = self.visitTypeArgumentList(type_args_list[0])
    else:
      if len(type_args_list) == 1:
        struct_type_args = self.visitTypeArgumentList(type_args_list[0])

    members = [self.visit(m) for m in ctx.implMember()]

    # Infer type parameters from type arguments if not explicitly set via impl<T>
    KNOWN_PRIMITIVES = {"int", "float", "String", "bool", "none", "void"}
    for arg in trait_type_args + struct_type_args:
      if isinstance(arg, BasicTypeNode) and arg.name not in KNOWN_PRIMITIVES:
        if arg.name not in type_params:
          type_params.append(arg.name)

    node = ImplBlockNode(struct_name, trait_name, members, type_params=type_params, trait_type_args=trait_type_args, struct_type_args=struct_type_args)
    # Positioning for Language Server:
    struct_token = getattr(ctx.structName, "start", ctx.structName)
    node.struct_name_line = getattr(struct_token, "line", None)
    node.struct_name_column = getattr(struct_token, "column", None)
    node.struct_name_length = len(struct_name)
    if trait_name:
      t_tok = ctx.traitName
      trait_token = getattr(t_tok, "start", t_tok)
      node.trait_name_line = getattr(trait_token, "line", None)
      node.trait_name_column = getattr(trait_token, "column", None)
      node.trait_name_length = len(trait_name)
    return node

  def visitImplMember(self, ctx: SapphireParser.ImplMemberContext) -> ImplMemberNode:
    modifier = None
    if ctx.STATIC():
      modifier = "static"
    elif ctx.CONST():
      modifier = "const"
    func_decl = self.visit(ctx.functionDeclaration())
    return ImplMemberNode(modifier, func_decl)

  def visitTraitDeclaration(self, ctx: SapphireParser.TraitDeclarationContext) -> TraitDeclNode:
    name = ctx.IDENTIFIER().getText()
    type_params = self.visitTypeParamList(ctx.typeParamList()) if ctx.typeParamList() else []
    members = [self.visit(m) for m in ctx.traitMember()]
    node = TraitDeclNode(name, members, type_params=type_params)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitReturnTypeList(self, ctx: SapphireParser.ReturnTypeListContext) -> List[TypeNode]:
    return [self.visit(t) for t in ctx.type_()]

  def visitTraitMember(self, ctx: SapphireParser.TraitMemberContext) -> TraitMemberNode:
    annotations = [self.visit(a) for a in ctx.annotation()] if ctx.annotation() else []
    modifier = None
    if ctx.STATIC():
      modifier = "static"
    elif ctx.CONST():
      modifier = "const"
    name = ctx.IDENTIFIER().getText()
    type_params = self.visitTypeParamList(ctx.typeParamList()) if ctx.typeParamList() else []
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_types = self.visit(ctx.returnTypeList()) if ctx.returnTypeList() else []
    node = TraitMemberNode(name, params, return_types, modifier=modifier, annotations=annotations, type_params=type_params)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitFunctionDeclaration(self, ctx: SapphireParser.FunctionDeclarationContext) -> FuncDeclNode:
    annotations = [self.visit(a) for a in ctx.annotation()] if ctx.annotation() else []
    name = ctx.functionName().getText()
    tp_ctx = ctx.tp1 if ctx.tp1 else ctx.tp2
    type_params = self.visitTypeParamList(tp_ctx) if tp_ctx else []
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_types = self.visit(ctx.returnTypeList()) if ctx.returnTypeList() else []
    body = self.visit(ctx.block()) if ctx.block() else None
    node = FuncDeclNode(name, params, return_types, body, annotations=annotations, type_params=type_params)
    # Positioning for Language Server:
    name_token = ctx.functionName().IDENTIFIER().getSymbol() if ctx.functionName().IDENTIFIER() else ctx.functionName().INIT().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitParameterList(self, ctx: SapphireParser.ParameterListContext) -> List[ParameterNode]:
    return [self.visit(p) for p in ctx.parameter()]

  def visitParameter(self, ctx: SapphireParser.ParameterContext) -> ParameterNode:
    is_mutable = ctx.VAR() is not None
    if ctx.SELF():
      name = "self"
      name_token = ctx.SELF().getSymbol()
    else:
      name_token = ctx.IDENTIFIER().getSymbol() if ctx.IDENTIFIER() else ctx.start
      name = name_token.text if hasattr(name_token, "text") and name_token.text else "p"

    param_type = self.visit(ctx.type_()) if ctx.type_() else None
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    node = ParameterNode(is_mutable, name, param_type, default_expr)
    # Positioning for Language Server:
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text) if hasattr(name_token, "text") and name_token.text else len(name)
    return node

  def visitType(self, ctx: SapphireParser.TypeContext) -> TypeNode:
    if ctx.QUESTION():
      return OptionalTypeNode(self.visit(ctx.type_()) if ctx.type_() else self.visitChildren(ctx))
    elif ctx.baseType():
      return self.visit(ctx.baseType())
    elif ctx.functionType():
      return self.visit(ctx.functionType())
    elif ctx.collectionType():
      return self.visit(ctx.collectionType())
    else:
      return self.visit(ctx.type_())

  def visitCollectionType(self, ctx: SapphireParser.CollectionTypeContext) -> TypeNode:
    key_type = self.visit(ctx.keyType)
    if ctx.valType:
      val_type = self.visit(ctx.valType)
      return MapTypeNode(key_type, val_type)
    else:
      return ArrayTypeNode(key_type)


  def visitBaseType(self, ctx: SapphireParser.BaseTypeContext) -> BasicTypeNode:
    type_args = self.visitTypeArgumentList(ctx.typeArgumentList()) if ctx.typeArgumentList() else []
    name = ctx.identifierPath().getText() if ctx.identifierPath() else ctx.getText()
    node = BasicTypeNode(name, type_args=type_args)
    # Positioning for Language Server:
    token = ctx.start
    node.name_line = token.line
    node.name_column = token.column
    node.name_length = len(token.text)
    return node

  def visitFunctionType(self, ctx: SapphireParser.FunctionTypeContext) -> FunctionTypeNode:
    if ctx.returnTypeList():
      return_types = self.visit(ctx.returnTypeList())
      param_types = [self.visit(t) for t in ctx.type_()] if ctx.type_() else []
    else:
      param_types = [self.visit(t) for t in ctx.type_()[:-1]] if len(ctx.type_()) > 1 else []
      return_types = [self.visit(ctx.type_()[-1])]
    return FunctionTypeNode(param_types, return_types)

  def visitStatement(self, ctx: SapphireParser.StatementContext) -> Optional[StmtNode]:
    if ctx and ctx.getChildCount() > 0 and ctx.getChild(0) is not None:
      return self.visit(ctx.getChild(0))
    return None

  def visitBlock(self, ctx: SapphireParser.BlockContext) -> BlockNode:
    statements = [self.visit(s) for s in ctx.statement() if s is not None]
    statements = [s for s in statements if s is not None]
    return BlockNode(statements)

  def visitVarBinding(self, ctx: SapphireParser.VarBindingContext):
    name = ctx.IDENTIFIER().getText()
    val_type = self.visit(ctx.type_()) if ctx.type_() else None
    token = ctx.IDENTIFIER().getSymbol()
    return {"name": name, "val_type": val_type, "token": token}

  def visitVariableDeclarationStatement(
      self, ctx: SapphireParser.VariableDeclarationStatementContext
  ) -> VarDeclNode:
    annotations = [self.visit(a) for a in ctx.annotation()] if ctx.annotation() else []
    is_mutable = ctx.VAR() is not None
    bindings = [self.visitVarBinding(b) for b in ctx.varBindingList().varBinding()]
    names = [b["name"] for b in bindings]
    val_types = [b["val_type"] for b in bindings]
    exprs = [self.visit(e) for e in ctx.expressionList().expression()] if ctx.expressionList() else []
    node = VarDeclNode(is_mutable, names, val_types, exprs, annotations=annotations)
    if bindings:
      name_token = bindings[0]["token"]
      node.name_line = name_token.line
      node.name_column = name_token.column
      node.name_length = len(name_token.text)
    return node

  def visitAssignmentStatement(self, ctx: SapphireParser.AssignmentStatementContext) -> AssignmentNode:
    targets = [self.visit(t) for t in ctx.targetList().expression()]
    op = ctx.getChild(1).getText()
    exprs = [self.visit(e) for e in ctx.expressionList().expression()]
    return AssignmentNode(targets, op, exprs)

  def visitExpressionStatement(self, ctx: SapphireParser.ExpressionStatementContext) -> ExprStmtNode:
    return ExprStmtNode(self.visit(ctx.expression()))

  def visitReturnStatement(self, ctx: SapphireParser.ReturnStatementContext) -> ReturnNode:
    exprs = [self.visit(e) for e in ctx.expression()] if ctx.expression() else []
    return ReturnNode(exprs)

  def visitBreakStatement(self, ctx: SapphireParser.BreakStatementContext) -> BreakNode:
    return BreakNode()

  def visitContinueStatement(self, ctx: SapphireParser.ContinueStatementContext) -> ContinueNode:
    return ContinueNode()

  def visitIfStatement(self, ctx: SapphireParser.IfStatementContext) -> IfNode:
    else_block = None
    if ctx.block(1):
      else_block = self.visit(ctx.block(1))
    elif ctx.ifStatement():
      else_block = self.visit(ctx.ifStatement())

    init_binding = None
    if ctx.letOrVarBinding():
      init_binding = self.visit(ctx.letOrVarBinding())

    condition = None
    if ctx.expression():
      condition = self.visit(ctx.expression())

    then_block = self.visit(ctx.block(0))
    return IfNode(init_binding, condition, then_block, else_block)

  def visitWhileStatement(self, ctx: SapphireParser.WhileStatementContext) -> WhileNode:
    init_binding = None
    if ctx.letOrVarBinding():
      init_binding = self.visit(ctx.letOrVarBinding())

    condition = None
    if ctx.expression():
      condition = self.visit(ctx.expression())

    block = self.visit(ctx.block())
    return WhileNode(init_binding, condition, block)

  def visitGuardStatement(self, ctx: SapphireParser.GuardStatementContext) -> GuardStmtNode:
    clauses = []
    for clause_ctx in ctx.guardClause():
      clauses.append(self.visit(clause_ctx))
    else_block = self.visit(ctx.block())
    return GuardStmtNode(clauses, else_block)

  def visitGuardClause(self, ctx: SapphireParser.GuardClauseContext) -> GuardClauseNode:
    if ctx.letOrVarBinding():
      binding = self.visit(ctx.letOrVarBinding())
      return GuardClauseNode(binding=binding)
    else:
      condition = self.visit(ctx.expression())
      return GuardClauseNode(condition=condition)

  def visitLetOrVarBinding(self, ctx: SapphireParser.LetOrVarBindingContext) -> HeaderBindingNode:
    is_mutable = ctx.VAR() is not None
    is_unwrap = ctx.UNWRAP_ASSIGN() is not None
    expr = self.visit(ctx.expression())

    bindings = ctx.varBindingList().varBinding()
    let_names = [b.IDENTIFIER().getText() for b in bindings]
    let_name = let_names[0]
    type_node = self.visit(bindings[0].type_()) if bindings[0].type_() else None
    first_token = bindings[0].IDENTIFIER().getSymbol()

    node = HeaderBindingNode(is_mutable, let_name, type_node, expr, is_unwrap, let_names=let_names)
    node.let_name_line = first_token.line
    node.let_name_column = first_token.column
    node.let_name_length = len(first_token.text)
    return node

  def visitForStatement(self, ctx: SapphireParser.ForStatementContext) -> ForNode:
    is_mutable = ctx.VAR() is not None
    id_nodes = ctx.IDENTIFIER()
    if len(id_nodes) == 2:
      key_token = id_nodes[0].getSymbol()
      val_token = id_nodes[1].getSymbol()
      key_var = key_token.text
      val_var = val_token.text
      loop_var = key_var
    else:
      key_token = None
      val_token = id_nodes[0].getSymbol()
      key_var = None
      val_var = val_token.text
      loop_var = val_var

    iterable = self.visit(ctx.expression())
    block = self.visit(ctx.block())
    node = ForNode(is_mutable, loop_var, iterable, block, key_var=key_var, val_var=val_var)
    if key_token:
      node.key_var_line = key_token.line
      node.key_var_column = key_token.column
      node.key_var_length = len(key_token.text)
    if val_token:
      node.val_var_line = val_token.line
      node.val_var_column = val_token.column
      node.val_var_length = len(val_token.text)

    var_token = key_token or val_token
    node.loop_var_line = var_token.line
    node.loop_var_column = var_token.column
    node.loop_var_length = len(var_token.text)
    return node

  # ==========================================
  # Expression labeled alternatives visitor
  # ==========================================

  def visitMultiplicativeExpr(self, ctx: SapphireParser.MultiplicativeExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitAdditiveExpr(self, ctx: SapphireParser.AdditiveExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitCompareExpr(self, ctx: SapphireParser.CompareExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitLogicalAndExpr(self, ctx: SapphireParser.LogicalAndExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "&&", right)

  def visitLogicalOrExpr(self, ctx: SapphireParser.LogicalOrExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "||", right)

  def visitTernaryExpr(self, ctx: SapphireParser.TernaryExprContext) -> TernaryExprNode:
    condition = self.visit(ctx.expression(0))
    true_expr = self.visit(ctx.expression(1))
    false_expr = self.visit(ctx.expression(2))
    return TernaryExprNode(condition, true_expr, false_expr)

  def visitCoalesceExpr(self, ctx: SapphireParser.CoalesceExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "??", right)

  def visitUnaryExpr(self, ctx: SapphireParser.UnaryExprContext) -> UnaryOpNode:
    op = ctx.getChild(0).getText()
    expr = self.visit(ctx.expression())
    return UnaryOpNode(op, expr)

  def visitCastExpr(self, ctx: SapphireParser.CastExprContext) -> CastExprNode:
    expr = self.visit(ctx.expression())
    target_type = self.visit(ctx.type_())
    return CastExprNode(expr, target_type)

  def visitCloneExpr(self, ctx: SapphireParser.CloneExprContext) -> CloneNode:
    expr = self.visit(ctx.expression(0))
    initializer_block = None
    if ctx.statement():
      initializer_block = [self.visit(s) for s in ctx.statement()]
    arena_expr = None
    if ctx.IN() is not None:
      arena_expr = self.visit(ctx.expression(1))
    return CloneNode(expr, initializer_block, arena_expr)

  def visitIndexExpr(self, ctx: SapphireParser.IndexExprContext) -> IndexExprNode:
    array = self.visit(ctx.expression(0))
    index = self.visit(ctx.expression(1))
    return IndexExprNode(array, index)

  def visitCallExpr(self, ctx: SapphireParser.CallExprContext) -> CallNode:
    callee = self.visit(ctx.expression())
    type_args = self.visitTypeArgumentList(ctx.typeArgumentList()) if ctx.typeArgumentList() else []
    args = self.visit(ctx.argumentList()) if ctx.argumentList() else []
    return CallNode(callee, args, type_args=type_args)

  def visitArgumentList(self, ctx: SapphireParser.ArgumentListContext) -> List[ArgumentNode]:
    return [self.visit(arg) for arg in ctx.argument()]

  def visitArgument(self, ctx: SapphireParser.ArgumentContext) -> ArgumentNode:
    if ctx.IDENTIFIER():
      name = ctx.IDENTIFIER().getText()
      expr = self.visit(ctx.expression())
      node = ArgumentNode(name, expr)
      # Positioning for Language Server:
      name_token = ctx.IDENTIFIER().getSymbol()
      node.name_line = name_token.line
      node.name_column = name_token.column
      node.name_length = len(name_token.text)
      return node
    else:
      expr = self.visit(ctx.expression())
      return ArgumentNode(None, expr)

  def visitMemberAccessExpr(self, ctx: SapphireParser.MemberAccessExprContext) -> MemberAccessNode:
    receiver = self.visit(ctx.expression())
    is_optional = ctx.OPT_DOT() is not None
    member = ctx.memberAccess().getText()
    node = MemberAccessNode(receiver, member, is_optional)
    # Positioning for Language Server:
    member_token = ctx.memberAccess().start
    node.member_line = member_token.line
    node.member_column = member_token.column
    node.member_length = len(member_token.text)
    return node

  def visitLambdaExpr(self, ctx: SapphireParser.LambdaExprContext) -> LambdaNode:
    return self.visit(ctx.lambdaExpression())

  def visitLambdaExpression(self, ctx: SapphireParser.LambdaExpressionContext) -> LambdaNode:
    params = self.visit(ctx.lambdaParameters())
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    body_ctx = ctx.block() if ctx.block() else ctx.expression()
    body = self.visit(body_ctx)
    return LambdaNode(params, return_type, body)

  def visitLambdaParameters(self, ctx: SapphireParser.LambdaParametersContext) -> List[LambdaParamNode]:
    if ctx.IDENTIFIER():
      return [LambdaParamNode(ctx.IDENTIFIER().getText(), None)]
    else:
      return [self.visit(p) for p in ctx.lambdaParameter()]

  def visitLambdaParameter(self, ctx: SapphireParser.LambdaParameterContext) -> LambdaParamNode:
    name = ctx.IDENTIFIER().getText()
    param_type = self.visit(ctx.type_()) if ctx.type_() else None
    return LambdaParamNode(name, param_type)

  def visitPrimaryExpr(self, ctx: SapphireParser.PrimaryExprContext) -> ASTNode:
    return self.visit(ctx.primaryExpression())

  def visitPrimaryExpression(self, ctx: SapphireParser.PrimaryExpressionContext) -> ASTNode:
    if ctx.literal():
      return self.visit(ctx.literal())
    elif ctx.IDENTIFIER():
      node = IdentifierNode(ctx.IDENTIFIER().getText())
      token = ctx.IDENTIFIER().getSymbol()
      node.name_line = token.line
      node.name_column = token.column
      node.name_length = len(token.text)
      return node
    elif ctx.SELF():
      node = IdentifierNode("self")
      token = ctx.SELF().getSymbol()
      node.name_line = token.line
      node.name_column = token.column
      node.name_length = len(token.text)
      return node
    elif ctx.arrayLiteral():
      return self.visit(ctx.arrayLiteral())
    elif ctx.mapLiteral():
      return self.visit(ctx.mapLiteral())
    elif ctx.structInitializer():
      return self.visit(ctx.structInitializer())
    elif ctx.matchExpression():
      return self.visit(ctx.matchExpression())
    else:
      node = self.visit(ctx.expression())
      if isinstance(node, ASTNode):
        node.is_parenthesized = True
      return node

  def visitLiteral(self, ctx: SapphireParser.LiteralContext) -> ASTNode:
    if ctx.INT_LIT():
      return LiteralNode(int(ctx.INT_LIT().getText()), "int")
    elif ctx.FLOAT_LIT():
      return LiteralNode(float(ctx.FLOAT_LIT().getText()), "float")
    elif ctx.STRING_LIT():
      val = ctx.STRING_LIT().getText()[1:-1]
      return LiteralNode(val, "string")
    elif ctx.INTERPOLATED_STRING_LIT():
      raw_text = ctx.INTERPOLATED_STRING_LIT().getText()[2:-1]
      return self._parse_interpolated_string(raw_text)
    elif ctx.TRUE():
      return LiteralNode(True, "bool")
    elif ctx.FALSE():
      return LiteralNode(False, "bool")
    else:
      return LiteralNode(None, "none")

  def _parse_interpolated_string(self, raw_text: str) -> InterpolatedStringNode:
    from antlr4 import InputStream, CommonTokenStream
    from src.parser.gen.SapphireLexer import SapphireLexer
    from src.parser.gen.SapphireParser import SapphireParser


    parts = []
    current_lit = []
    i = 0
    n = len(raw_text)

    while i < n:
      ch = raw_text[i]
      if ch == '{':
        if i + 1 < n and raw_text[i + 1] == '{':
          current_lit.append('{')
          i += 2
          continue
        if current_lit:
          parts.append(LiteralNode("".join(current_lit), "string"))
          current_lit = []
        i += 1
        start_expr = i
        brace_depth = 1
        in_quote = False
        quote_char = None

        while i < n and brace_depth > 0:
          c = raw_text[i]
          if c == '\\':
            i += 2
            continue
          if in_quote:
            if c == quote_char:
              in_quote = False
              quote_char = None
          else:
            if c in ('"', "'"):
              in_quote = True
              quote_char = c
            elif c == '{':
              brace_depth += 1
            elif c == '}':
              brace_depth -= 1
          if brace_depth > 0:
            i += 1

        expr_str = raw_text[start_expr:i]
        i += 1  # Skip closing '}'

        lexer = SapphireLexer(InputStream(expr_str))
        tokens = CommonTokenStream(lexer)
        parser = SapphireParser(tokens)
        expr_tree = parser.expression()
        expr_ast = self.visit(expr_tree)
        parts.append(expr_ast)

      elif ch == '}':
        if i + 1 < n and raw_text[i + 1] == '}':
          current_lit.append('}')
          i += 2
          continue
        else:
          current_lit.append(ch)
          i += 1
      elif ch == '\\':
        if i + 1 < n:
          next_ch = raw_text[i + 1]
          if next_ch == 'n':
            current_lit.append('\n')
          elif next_ch == 't':
            current_lit.append('\t')
          elif next_ch == 'r':
            current_lit.append('\r')
          elif next_ch in ('"', '\\', '{', '}'):
            current_lit.append(next_ch)
          else:
            current_lit.append('\\' + next_ch)
          i += 2
        else:
          current_lit.append(ch)
          i += 1
      else:
        current_lit.append(ch)
        i += 1

    if current_lit:
      parts.append(LiteralNode("".join(current_lit), "string"))

    return InterpolatedStringNode(parts)

  def visitArrayLiteral(self, ctx: SapphireParser.ArrayLiteralContext) -> ArrayLiteralNode:
    elements = [self.visit(expr) for expr in ctx.expression()]
    return ArrayLiteralNode(elements)

  def visitMapLiteral(self, ctx: SapphireParser.MapLiteralContext) -> MapLiteralNode:
    entries = [self.visit(entry) for entry in ctx.mapEntry()] if ctx.mapEntry() else []
    return MapLiteralNode(entries)

  def visitMapEntry(self, ctx: SapphireParser.MapEntryContext) -> MapEntryNode:
    key = self.visit(ctx.expression(0))
    value = self.visit(ctx.expression(1))
    return MapEntryNode(key, value)

  def visitStructInitializer(self, ctx: SapphireParser.StructInitializerContext) -> StructInitializerNode:
    struct_name = ctx.IDENTIFIER().getText()
    type_args = self.visitTypeArgumentList(ctx.typeArgumentList()) if ctx.typeArgumentList() else []
    fields = []
    if ctx.structInitFieldList():
      fields = self.visit(ctx.structInitFieldList())
    arena_expr = None
    if ctx.IN() is not None:
      arena_expr = self.visit(ctx.expression())
    node = StructInitializerNode(struct_name, fields, arena_expr, type_args=type_args)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitStructInitFieldList(self, ctx: SapphireParser.StructInitFieldListContext) -> List[ArgumentNode]:
    return [self.visit(field) for field in ctx.structInitField()]

  def visitStructInitField(self, ctx: SapphireParser.StructInitFieldContext) -> ArgumentNode:
    name = ctx.IDENTIFIER().getText()
    expr_ctx = ctx.expression()
    if expr_ctx is None:
      raise SyntaxError(f"Field '{name}' in struct initializer must be assigned an expression using '='.")
    expr = self.visit(expr_ctx)
    node = ArgumentNode(name, expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitYieldStatement(self, ctx: SapphireParser.YieldStatementContext) -> YieldNode:
    exprs = [self.visit(e) for e in ctx.expression()] if ctx.expression() else []
    return YieldNode(exprs)

  def visitMatchExpression(self, ctx: SapphireParser.MatchExpressionContext) -> MatchExprNode:
    subject = self.visit(ctx.expression())
    cases = [self.visit(case_ctx) for case_ctx in ctx.matchCase()]
    return MatchExprNode(subject, cases)

  def visitMatchCase(self, ctx: SapphireParser.MatchCaseContext) -> MatchCaseNode:
    pattern = self.visit(ctx.matchPattern())
    if ctx.block():
      body = self.visit(ctx.block())
    else:
      body = self.visit(ctx.expression())
    return MatchCaseNode(pattern, body)

  def visitMatchPattern(self, ctx: SapphireParser.MatchPatternContext) -> ASTNode:
    if ctx.ELLIPSIS():
      return EllipsisPatternNode()
    return self.visit(ctx.expression())
