"""Visitor implementation for building Sapphire AST from ANTLR parse tree.

This module walks the parse tree generated by the ANTLR parser and constructs
a strongly typed abstract syntax tree (AST) using the node classes defined in
ast.py.
"""

from typing import List

from parser.ast import *
from parser.gen.SapphireVisitor import SapphireVisitor
from parser.gen.SapphireParser import SapphireParser


class ASTBuilder(SapphireVisitor):
  """Walks the ANTLR Parse Tree and constructs a Sapphire AST."""

  def visit(self, tree):
    # This override is only needed for the language server to track token locations.
    # It does not affect compilation/transpilation.
    node = super().visit(tree)
    if isinstance(node, ASTNode) and tree is not None:
      if hasattr(tree, "start") and tree.start is not None:
        node.start_line = tree.start.line
        node.start_column = tree.start.column
        if hasattr(tree, "stop") and tree.stop is not None:
          node.end_line = tree.stop.line
          node.end_column = tree.stop.column + len(tree.stop.text)
          if node.start_line == node.end_line:
            node.length = node.end_column - node.start_column
    return node

  def visitProgram(self, ctx: SapphireParser.ProgramContext) -> ProgramNode:
    declarations = [self.visit(decl) for decl in ctx.declaration()]
    return ProgramNode(declarations)

  def visitDeclaration(self, ctx: SapphireParser.DeclarationContext) -> DeclNode:
    return self.visit(ctx.getChild(0))

  def visitStructDeclaration(self, ctx: SapphireParser.StructDeclarationContext) -> StructDeclNode:
    name = ctx.IDENTIFIER(0).getText()
    parent_name = ctx.IDENTIFIER(1).getText() if len(ctx.IDENTIFIER()) > 1 else None
    fields = [self.visit(field) for field in ctx.structField()]
    is_prototype = ctx.PROTO_KEYWORD() is not None
    node = StructDeclNode(name, parent_name, fields, is_prototype)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER(0).getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    if parent_name:
      parent_token = ctx.IDENTIFIER(1).getSymbol()
      node.parent_name_line = parent_token.line
      node.parent_name_column = parent_token.column
      node.parent_name_length = len(parent_token.text)
    return node

  def visitStructField(self, ctx: SapphireParser.StructFieldContext) -> StructFieldNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    field_type = self.visit(ctx.type_())
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    node = StructFieldNode(is_mutable, name, field_type, default_expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitImplBlock(self, ctx: SapphireParser.ImplBlockContext) -> ImplBlockNode:
    trait_name = ctx.traitName.text if ctx.traitName else None
    struct_name = ctx.structName.text
    members = [self.visit(m) for m in ctx.implMember()]
    node = ImplBlockNode(struct_name, trait_name, members)
    # Positioning for Language Server:
    struct_token = ctx.structName
    node.struct_name_line = struct_token.line
    node.struct_name_column = struct_token.column
    node.struct_name_length = len(struct_token.text)
    if trait_name:
      trait_token = ctx.traitName
      node.trait_name_line = trait_token.line
      node.trait_name_column = trait_token.column
      node.trait_name_length = len(trait_token.text)
    return node

  def visitImplMember(self, ctx: SapphireParser.ImplMemberContext) -> ImplMemberNode:
    modifier = None
    if ctx.STATIC():
      modifier = "static"
    elif ctx.CONST():
      modifier = "const"
    func_decl = self.visit(ctx.functionDeclaration())
    return ImplMemberNode(modifier, func_decl)

  def visitTraitDeclaration(self, ctx: SapphireParser.TraitDeclarationContext) -> TraitDeclNode:
    name = ctx.IDENTIFIER().getText()
    members = [self.visit(m) for m in ctx.traitMember()]
    node = TraitDeclNode(name, members)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitTraitMember(self, ctx: SapphireParser.TraitMemberContext) -> TraitMemberNode:
    name = ctx.IDENTIFIER().getText()
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    node = TraitMemberNode(name, params, return_type)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitFunctionDeclaration(self, ctx: SapphireParser.FunctionDeclarationContext) -> FuncDeclNode:
    name = ctx.functionName().getText()
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    body = self.visit(ctx.block())
    node = FuncDeclNode(name, params, return_type, body)
    # Positioning for Language Server:
    name_token = ctx.functionName().IDENTIFIER().getSymbol() if ctx.functionName().IDENTIFIER() else ctx.functionName().INIT().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitParameterList(self, ctx: SapphireParser.ParameterListContext) -> List[ParameterNode]:
    return [self.visit(p) for p in ctx.parameter()]

  def visitParameter(self, ctx: SapphireParser.ParameterContext) -> ParameterNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    param_type = self.visit(ctx.type_())
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    node = ParameterNode(is_mutable, name, param_type, default_expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitType(self, ctx: SapphireParser.TypeContext) -> TypeNode:
    if ctx.QUESTION():
      return OptionalTypeNode(self.visit(ctx.type_()) if ctx.type_() else self.visitChildren(ctx))
    elif ctx.baseType():
      return self.visit(ctx.baseType())
    else:
      return self.visit(ctx.functionType())

  def visitBaseType(self, ctx: SapphireParser.BaseTypeContext) -> BasicTypeNode:
    node = BasicTypeNode(ctx.getText())
    # Positioning for Language Server:
    token = ctx.start
    node.name_line = token.line
    node.name_column = token.column
    node.name_length = len(token.text)
    return node

  def visitFunctionType(self, ctx: SapphireParser.FunctionTypeContext) -> FunctionTypeNode:
    param_types = [self.visit(t) for t in ctx.type_()[:-1]]
    return_type = self.visit(ctx.type_()[-1])
    return FunctionTypeNode(param_types, return_type)

  def visitStatement(self, ctx: SapphireParser.StatementContext) -> StmtNode:
    return self.visit(ctx.getChild(0))

  def visitBlock(self, ctx: SapphireParser.BlockContext) -> BlockNode:
    statements = [self.visit(s) for s in ctx.statement()]
    return BlockNode(statements)

  def visitVariableDeclarationStatement(
      self, ctx: SapphireParser.VariableDeclarationStatementContext
  ) -> VarDeclNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    val_type = self.visit(ctx.type_()) if ctx.type_() else None
    expr = self.visit(ctx.expression())
    node = VarDeclNode(is_mutable, name, val_type, expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitAssignmentStatement(self, ctx: SapphireParser.AssignmentStatementContext) -> AssignmentNode:
    target = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    expr = self.visit(ctx.expression(1))
    return AssignmentNode(target, op, expr)

  def visitExpressionStatement(self, ctx: SapphireParser.ExpressionStatementContext) -> ExprStmtNode:
    return ExprStmtNode(self.visit(ctx.expression()))

  def visitReturnStatement(self, ctx: SapphireParser.ReturnStatementContext) -> ReturnNode:
    expr = self.visit(ctx.expression()) if ctx.expression() else None
    return ReturnNode(expr)

  def visitIfStatement(self, ctx: SapphireParser.IfStatementContext) -> IfNode:
    is_if_let = ctx.LET() is not None
    else_block = None
    if ctx.block(1):
      else_block = self.visit(ctx.block(1))
    elif ctx.ifStatement():
      else_block = self.visit(ctx.ifStatement())

    if is_if_let:
      let_name = ctx.IDENTIFIER().getText()
      expr = self.visit(ctx.expression())
      then_block = self.visit(ctx.block(0))
      node = IfNode(expr, then_block, else_block, is_if_let=True, let_name=let_name)
      let_token = ctx.IDENTIFIER().getSymbol()
      node.let_name_line = let_token.line
      node.let_name_column = let_token.column
      node.let_name_length = len(let_token.text)
    else:
      expr = self.visit(ctx.expression())
      then_block = self.visit(ctx.block(0))
      node = IfNode(expr, then_block, else_block)
    return node

  def visitWhileStatement(self, ctx: SapphireParser.WhileStatementContext) -> WhileNode:
    condition = self.visit(ctx.expression())
    block = self.visit(ctx.block())
    return WhileNode(condition, block)

  def visitForStatement(self, ctx: SapphireParser.ForStatementContext) -> ForNode:
    is_mutable = ctx.VAR() is not None
    loop_var = ctx.IDENTIFIER().getText()
    iterable = self.visit(ctx.expression())
    block = self.visit(ctx.block())
    node = ForNode(is_mutable, loop_var, iterable, block)
    var_token = ctx.IDENTIFIER().getSymbol()
    node.loop_var_line = var_token.line
    node.loop_var_column = var_token.column
    node.loop_var_length = len(var_token.text)
    return node

  # ==========================================
  # Expression labeled alternatives visitor
  # ==========================================

  def visitMultiplicativeExpr(self, ctx: SapphireParser.MultiplicativeExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitAdditiveExpr(self, ctx: SapphireParser.AdditiveExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitCompareExpr(self, ctx: SapphireParser.CompareExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitLogicalAndExpr(self, ctx: SapphireParser.LogicalAndExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "&&", right)

  def visitLogicalOrExpr(self, ctx: SapphireParser.LogicalOrExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "||", right)

  def visitUnaryExpr(self, ctx: SapphireParser.UnaryExprContext) -> UnaryOpNode:
    op = ctx.getChild(0).getText()
    expr = self.visit(ctx.expression())
    return UnaryOpNode(op, expr)

  def visitCloneExpr(self, ctx: SapphireParser.CloneExprContext) -> CloneNode:
    expr = self.visit(ctx.expression(0))
    initializer_block = None
    if ctx.statement():
      initializer_block = [self.visit(s) for s in ctx.statement()]
    arena_expr = None
    if ctx.IN() is not None:
      arena_expr = self.visit(ctx.expression(1))
    return CloneNode(expr, initializer_block, arena_expr)

  def visitIndexExpr(self, ctx: SapphireParser.IndexExprContext) -> IndexExprNode:
    array = self.visit(ctx.expression(0))
    index = self.visit(ctx.expression(1))
    return IndexExprNode(array, index)

  def visitCallExpr(self, ctx: SapphireParser.CallExprContext) -> CallNode:
    callee = self.visit(ctx.expression())
    args = self.visit(ctx.argumentList()) if ctx.argumentList() else []
    return CallNode(callee, args)

  def visitArgumentList(self, ctx: SapphireParser.ArgumentListContext) -> List[ArgumentNode]:
    return [self.visit(arg) for arg in ctx.argument()]

  def visitArgument(self, ctx: SapphireParser.ArgumentContext) -> ArgumentNode:
    if ctx.IDENTIFIER():
      name = ctx.IDENTIFIER().getText()
      expr = self.visit(ctx.expression())
      node = ArgumentNode(name, expr)
      # Positioning for Language Server:
      name_token = ctx.IDENTIFIER().getSymbol()
      node.name_line = name_token.line
      node.name_column = name_token.column
      node.name_length = len(name_token.text)
      return node
    else:
      expr = self.visit(ctx.expression())
      return ArgumentNode(None, expr)

  def visitMemberAccessExpr(self, ctx: SapphireParser.MemberAccessExprContext) -> MemberAccessNode:
    receiver = self.visit(ctx.expression())
    is_optional = ctx.OPT_DOT() is not None
    member = ctx.memberAccess().getText()
    node = MemberAccessNode(receiver, member, is_optional)
    # Positioning for Language Server:
    member_token = ctx.memberAccess().start
    node.member_line = member_token.line
    node.member_column = member_token.column
    node.member_length = len(member_token.text)
    return node

  def visitLambdaExpr(self, ctx: SapphireParser.LambdaExprContext) -> LambdaNode:
    return self.visit(ctx.lambdaExpression())

  def visitLambdaExpression(self, ctx: SapphireParser.LambdaExpressionContext) -> LambdaNode:
    params = self.visit(ctx.lambdaParameters())
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    body_ctx = ctx.block() if ctx.block() else ctx.expression()
    body = self.visit(body_ctx)
    return LambdaNode(params, return_type, body)

  def visitLambdaParameters(self, ctx: SapphireParser.LambdaParametersContext) -> List[LambdaParamNode]:
    if ctx.IDENTIFIER():
      return [LambdaParamNode(ctx.IDENTIFIER().getText(), None)]
    else:
      return [self.visit(p) for p in ctx.lambdaParameter()]

  def visitLambdaParameter(self, ctx: SapphireParser.LambdaParameterContext) -> LambdaParamNode:
    name = ctx.IDENTIFIER().getText()
    param_type = self.visit(ctx.type_()) if ctx.type_() else None
    return LambdaParamNode(name, param_type)

  def visitPrimaryExpr(self, ctx: SapphireParser.PrimaryExprContext) -> ASTNode:
    return self.visit(ctx.primaryExpression())

  def visitPrimaryExpression(self, ctx: SapphireParser.PrimaryExpressionContext) -> ASTNode:
    if ctx.literal():
      return self.visit(ctx.literal())
    elif ctx.IDENTIFIER():
      node = IdentifierNode(ctx.IDENTIFIER().getText())
      token = ctx.IDENTIFIER().getSymbol()
      node.name_line = token.line
      node.name_column = token.column
      node.name_length = len(token.text)
      return node
    elif ctx.SELF():
      node = IdentifierNode("self")
      token = ctx.SELF().getSymbol()
      node.name_line = token.line
      node.name_column = token.column
      node.name_length = len(token.text)
      return node
    elif ctx.arrayLiteral():
      return self.visit(ctx.arrayLiteral())
    elif ctx.structInitializer():
      return self.visit(ctx.structInitializer())
    else:
      return self.visit(ctx.expression())

  def visitLiteral(self, ctx: SapphireParser.LiteralContext) -> LiteralNode:
    if ctx.INT_LIT():
      return LiteralNode(int(ctx.INT_LIT().getText()), "int")
    elif ctx.FLOAT_LIT():
      return LiteralNode(float(ctx.FLOAT_LIT().getText()), "float")
    elif ctx.STRING_LIT():
      val = ctx.STRING_LIT().getText()[1:-1]
      return LiteralNode(val, "string")
    elif ctx.TRUE():
      return LiteralNode(True, "bool")
    elif ctx.FALSE():
      return LiteralNode(False, "bool")
    else:
      return LiteralNode(None, "none")

  def visitArrayLiteral(self, ctx: SapphireParser.ArrayLiteralContext) -> ArrayLiteralNode:
    elements = [self.visit(expr) for expr in ctx.expression()]
    return ArrayLiteralNode(elements)

  def visitStructInitializer(self, ctx: SapphireParser.StructInitializerContext) -> StructInitializerNode:
    struct_name = ctx.IDENTIFIER().getText()
    fields = []
    if ctx.structInitFieldList():
      fields = self.visit(ctx.structInitFieldList())
    arena_expr = None
    if ctx.IN() is not None:
      arena_expr = self.visit(ctx.expression())
    node = StructInitializerNode(struct_name, fields, arena_expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node

  def visitStructInitFieldList(self, ctx: SapphireParser.StructInitFieldListContext) -> List[ArgumentNode]:
    return [self.visit(field) for field in ctx.structInitField()]

  def visitStructInitField(self, ctx: SapphireParser.StructInitFieldContext) -> ArgumentNode:
    name = ctx.IDENTIFIER().getText()
    expr = self.visit(ctx.expression())
    node = ArgumentNode(name, expr)
    # Positioning for Language Server:
    name_token = ctx.IDENTIFIER().getSymbol()
    node.name_line = name_token.line
    node.name_column = name_token.column
    node.name_length = len(name_token.text)
    return node
