"""Visitor implementation for building Sapphire AST from ANTLR parse tree.

This module walks the parse tree generated by the ANTLR parser and constructs
a strongly typed abstract syntax tree (AST) using the node classes defined in
ast.py.
"""

from typing import List

from parser.ast import *
from parser.gen.SapphireVisitor import SapphireVisitor
from parser.gen.SapphireParser import SapphireParser


class ASTBuilder(SapphireVisitor):
  """Walks the ANTLR Parse Tree and constructs a Sapphire AST."""

  def visitProgram(self, ctx: SapphireParser.ProgramContext) -> ProgramNode:
    declarations = [self.visit(decl) for decl in ctx.declaration()]
    return ProgramNode(declarations)

  def visitDeclaration(self, ctx: SapphireParser.DeclarationContext) -> DeclNode:
    return self.visit(ctx.getChild(0))

  def visitStructDeclaration(self, ctx: SapphireParser.StructDeclarationContext) -> StructDeclNode:
    name = ctx.IDENTIFIER(0).getText()
    parent_name = ctx.IDENTIFIER(1).getText() if len(ctx.IDENTIFIER()) > 1 else None
    fields = [self.visit(field) for field in ctx.structField()]
    is_prototype = ctx.PROTO_KEYWORD() is not None
    return StructDeclNode(name, parent_name, fields, is_prototype)

  def visitStructField(self, ctx: SapphireParser.StructFieldContext) -> StructFieldNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    field_type = self.visit(ctx.type_())
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    return StructFieldNode(is_mutable, name, field_type, default_expr)

  def visitImplBlock(self, ctx: SapphireParser.ImplBlockContext) -> ImplBlockNode:
    trait_name = ctx.traitName.text if ctx.traitName else None
    struct_name = ctx.structName.text
    members = [self.visit(m) for m in ctx.implMember()]
    return ImplBlockNode(struct_name, trait_name, members)

  def visitImplMember(self, ctx: SapphireParser.ImplMemberContext) -> ImplMemberNode:
    modifier = None
    if ctx.STATIC():
      modifier = "static"
    elif ctx.CONST():
      modifier = "const"
    func_decl = self.visit(ctx.functionDeclaration())
    return ImplMemberNode(modifier, func_decl)

  def visitTraitDeclaration(self, ctx: SapphireParser.TraitDeclarationContext) -> TraitDeclNode:
    name = ctx.IDENTIFIER().getText()
    members = [self.visit(m) for m in ctx.traitMember()]
    return TraitDeclNode(name, members)

  def visitTraitMember(self, ctx: SapphireParser.TraitMemberContext) -> TraitMemberNode:
    name = ctx.IDENTIFIER().getText()
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    return TraitMemberNode(name, params, return_type)

  def visitFunctionDeclaration(self, ctx: SapphireParser.FunctionDeclarationContext) -> FuncDeclNode:
    name = ctx.functionName().getText()
    params = self.visit(ctx.parameterList()) if ctx.parameterList() else []
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    body = self.visit(ctx.block())
    return FuncDeclNode(name, params, return_type, body)

  def visitParameterList(self, ctx: SapphireParser.ParameterListContext) -> List[ParameterNode]:
    return [self.visit(p) for p in ctx.parameter()]

  def visitParameter(self, ctx: SapphireParser.ParameterContext) -> ParameterNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    param_type = self.visit(ctx.type_())
    default_expr = self.visit(ctx.expression()) if ctx.expression() else None
    return ParameterNode(is_mutable, name, param_type, default_expr)

  def visitType(self, ctx: SapphireParser.TypeContext) -> TypeNode:
    if ctx.QUESTION():
      return OptionalTypeNode(self.visit(ctx.type_()) if ctx.type_() else self.visitChildren(ctx))
    elif ctx.baseType():
      return self.visit(ctx.baseType())
    else:
      return self.visit(ctx.functionType())

  def visitBaseType(self, ctx: SapphireParser.BaseTypeContext) -> BasicTypeNode:
    return BasicTypeNode(ctx.getText())

  def visitFunctionType(self, ctx: SapphireParser.FunctionTypeContext) -> FunctionTypeNode:
    param_types = [self.visit(t) for t in ctx.type_()[:-1]]
    return_type = self.visit(ctx.type_()[-1])
    return FunctionTypeNode(param_types, return_type)

  def visitStatement(self, ctx: SapphireParser.StatementContext) -> StmtNode:
    return self.visit(ctx.getChild(0))

  def visitBlock(self, ctx: SapphireParser.BlockContext) -> BlockNode:
    statements = [self.visit(s) for s in ctx.statement()]
    return BlockNode(statements)

  def visitVariableDeclarationStatement(
      self, ctx: SapphireParser.VariableDeclarationStatementContext
  ) -> VarDeclNode:
    is_mutable = ctx.VAR() is not None
    name = ctx.IDENTIFIER().getText()
    val_type = self.visit(ctx.type_()) if ctx.type_() else None
    expr = self.visit(ctx.expression())
    return VarDeclNode(is_mutable, name, val_type, expr)

  def visitAssignmentStatement(self, ctx: SapphireParser.AssignmentStatementContext) -> AssignmentNode:
    target = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    expr = self.visit(ctx.expression(1))
    return AssignmentNode(target, op, expr)

  def visitExpressionStatement(self, ctx: SapphireParser.ExpressionStatementContext) -> ExprStmtNode:
    return ExprStmtNode(self.visit(ctx.expression()))

  def visitReturnStatement(self, ctx: SapphireParser.ReturnStatementContext) -> ReturnNode:
    expr = self.visit(ctx.expression()) if ctx.expression() else None
    return ReturnNode(expr)

  def visitIfStatement(self, ctx: SapphireParser.IfStatementContext) -> IfNode:
    is_if_let = ctx.LET() is not None
    else_block = None
    if ctx.block(1):
      else_block = self.visit(ctx.block(1))
    elif ctx.ifStatement():
      else_block = self.visit(ctx.ifStatement())

    if is_if_let:
      let_name = ctx.IDENTIFIER().getText()
      expr = self.visit(ctx.expression())
      then_block = self.visit(ctx.block(0))
      return IfNode(expr, then_block, else_block, is_if_let=True, let_name=let_name)
    else:
      expr = self.visit(ctx.expression())
      then_block = self.visit(ctx.block(0))
      return IfNode(expr, then_block, else_block)

  def visitWhileStatement(self, ctx: SapphireParser.WhileStatementContext) -> WhileNode:
    condition = self.visit(ctx.expression())
    block = self.visit(ctx.block())
    return WhileNode(condition, block)

  def visitForStatement(self, ctx: SapphireParser.ForStatementContext) -> ForNode:
    is_mutable = ctx.VAR() is not None
    loop_var = ctx.IDENTIFIER().getText()
    iterable = self.visit(ctx.expression())
    block = self.visit(ctx.block())
    return ForNode(is_mutable, loop_var, iterable, block)

  # ==========================================
  # Expression labeled alternatives visitor
  # ==========================================

  def visitMultiplicativeExpr(self, ctx: SapphireParser.MultiplicativeExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitAdditiveExpr(self, ctx: SapphireParser.AdditiveExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitCompareExpr(self, ctx: SapphireParser.CompareExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    op = ctx.getChild(1).getText()
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, op, right)

  def visitLogicalAndExpr(self, ctx: SapphireParser.LogicalAndExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "&&", right)

  def visitLogicalOrExpr(self, ctx: SapphireParser.LogicalOrExprContext) -> BinaryOpNode:
    left = self.visit(ctx.expression(0))
    right = self.visit(ctx.expression(1))
    return BinaryOpNode(left, "||", right)

  def visitUnaryExpr(self, ctx: SapphireParser.UnaryExprContext) -> UnaryOpNode:
    op = ctx.getChild(0).getText()
    expr = self.visit(ctx.expression())
    return UnaryOpNode(op, expr)

  def visitCloneExpr(self, ctx: SapphireParser.CloneExprContext) -> CloneNode:
    expr = self.visit(ctx.expression())
    initializer_block = None
    if ctx.statement():
      initializer_block = [self.visit(s) for s in ctx.statement()]
    return CloneNode(expr, initializer_block)

  def visitIndexExpr(self, ctx: SapphireParser.IndexExprContext) -> IndexExprNode:
    array = self.visit(ctx.expression(0))
    index = self.visit(ctx.expression(1))
    return IndexExprNode(array, index)

  def visitCallExpr(self, ctx: SapphireParser.CallExprContext) -> CallNode:
    callee = self.visit(ctx.expression())
    args = self.visit(ctx.argumentList()) if ctx.argumentList() else []
    return CallNode(callee, args)

  def visitArgumentList(self, ctx: SapphireParser.ArgumentListContext) -> List[ArgumentNode]:
    return [self.visit(arg) for arg in ctx.argument()]

  def visitArgument(self, ctx: SapphireParser.ArgumentContext) -> ArgumentNode:
    if ctx.IDENTIFIER():
      name = ctx.IDENTIFIER().getText()
      expr = self.visit(ctx.expression())
      return ArgumentNode(name, expr)
    else:
      expr = self.visit(ctx.expression())
      return ArgumentNode(None, expr)

  def visitMemberAccessExpr(self, ctx: SapphireParser.MemberAccessExprContext) -> MemberAccessNode:
    receiver = self.visit(ctx.expression())
    is_optional = ctx.OPT_DOT() is not None
    member = ctx.memberAccess().getText()
    return MemberAccessNode(receiver, member, is_optional)

  def visitLambdaExpr(self, ctx: SapphireParser.LambdaExprContext) -> LambdaNode:
    return self.visit(ctx.lambdaExpression())

  def visitLambdaExpression(self, ctx: SapphireParser.LambdaExpressionContext) -> LambdaNode:
    params = self.visit(ctx.lambdaParameters())
    return_type = self.visit(ctx.type_()) if ctx.type_() else None
    body_ctx = ctx.block() if ctx.block() else ctx.expression()
    body = self.visit(body_ctx)
    return LambdaNode(params, return_type, body)

  def visitLambdaParameters(self, ctx: SapphireParser.LambdaParametersContext) -> List[LambdaParamNode]:
    if ctx.IDENTIFIER():
      return [LambdaParamNode(ctx.IDENTIFIER().getText(), None)]
    else:
      return [self.visit(p) for p in ctx.lambdaParameter()]

  def visitLambdaParameter(self, ctx: SapphireParser.LambdaParameterContext) -> LambdaParamNode:
    name = ctx.IDENTIFIER().getText()
    param_type = self.visit(ctx.type_()) if ctx.type_() else None
    return LambdaParamNode(name, param_type)

  def visitPrimaryExpr(self, ctx: SapphireParser.PrimaryExprContext) -> ASTNode:
    return self.visit(ctx.primaryExpression())

  def visitPrimaryExpression(self, ctx: SapphireParser.PrimaryExpressionContext) -> ASTNode:
    if ctx.literal():
      return self.visit(ctx.literal())
    elif ctx.IDENTIFIER():
      return IdentifierNode(ctx.IDENTIFIER().getText())
    elif ctx.SELF():
      return IdentifierNode("self")
    elif ctx.arrayLiteral():
      return self.visit(ctx.arrayLiteral())
    elif ctx.structInitializer():
      return self.visit(ctx.structInitializer())
    else:
      return self.visit(ctx.expression())

  def visitLiteral(self, ctx: SapphireParser.LiteralContext) -> LiteralNode:
    if ctx.INT_LIT():
      return LiteralNode(int(ctx.INT_LIT().getText()), "int")
    elif ctx.FLOAT_LIT():
      return LiteralNode(float(ctx.FLOAT_LIT().getText()), "float")
    elif ctx.STRING_LIT():
      val = ctx.STRING_LIT().getText()[1:-1]
      return LiteralNode(val, "string")
    elif ctx.TRUE():
      return LiteralNode(True, "bool")
    elif ctx.FALSE():
      return LiteralNode(False, "bool")
    else:
      return LiteralNode(None, "none")

  def visitArrayLiteral(self, ctx: SapphireParser.ArrayLiteralContext) -> ArrayLiteralNode:
    elements = [self.visit(expr) for expr in ctx.expression()]
    return ArrayLiteralNode(elements)

  def visitStructInitializer(self, ctx: SapphireParser.StructInitializerContext) -> StructInitializerNode:
    struct_name = ctx.IDENTIFIER().getText()
    fields = []
    if ctx.structInitFieldList():
      fields = self.visit(ctx.structInitFieldList())
    return StructInitializerNode(struct_name, fields)

  def visitStructInitFieldList(self, ctx: SapphireParser.StructInitFieldListContext) -> List[ArgumentNode]:
    return [self.visit(field) for field in ctx.structInitField()]

  def visitStructInitField(self, ctx: SapphireParser.StructInitFieldContext) -> ArgumentNode:
    name = ctx.IDENTIFIER().getText()
    expr = self.visit(ctx.expression())
    return ArgumentNode(name, expr)
