"""Unit tests for the experimental Sapphire LLVM IR transpiler.

Validates that LLVM IR generated by LLVMTranspiler is correct and adheres
to LLVM IR specification (instruction selection, stack allocations, returns).
"""

import unittest
from antlr4 import CommonTokenStream, InputStream

try:
  from code_gen.base_transpiler import BaseTranspiler
  from code_gen.llvm_transpiler import LLVMTranspiler
  from parser.ast import (
      BasicTypeNode,
      FuncDeclNode,
      IdentifierNode,
      LiteralNode,
      ProgramNode,
      ReturnNode,
  )
  from parser.ast_builder import ASTBuilder
  from parser.gen.SapphireLexer import SapphireLexer
  from parser.gen.SapphireParser import SapphireParser
  from semantics.type_checker import TypeChecker
except ModuleNotFoundError:  # pragma: no cover
  from src.code_gen.base_transpiler import BaseTranspiler
  from src.code_gen.llvm_transpiler import LLVMTranspiler
  from src.parser.ast import (
      BasicTypeNode,
      FuncDeclNode,
      IdentifierNode,
      LiteralNode,
      ProgramNode,
      ReturnNode,
  )
  from src.parser.ast_builder import ASTBuilder
  from src.parser.gen.SapphireLexer import SapphireLexer
  from src.parser.gen.SapphireParser import SapphireParser
  from src.semantics.type_checker import TypeChecker


class TestLLVMTranspiler(unittest.TestCase):
  """Suite of unit tests verifying correct LLVM IR code generation."""

  def _parse_and_transpile(self, code: str) -> str:
    input_stream = InputStream(code)
    lexer = SapphireLexer(input_stream)
    lexer.removeErrorListeners()
    stream = CommonTokenStream(lexer)
    parser = SapphireParser(stream)
    parser.removeErrorListeners()
    tree = parser.program()

    builder = ASTBuilder()
    ast = builder.visit(tree)

    try:
      checker = TypeChecker()
      checker.check(ast)
    except Exception:
      pass

    transpiler = LLVMTranspiler()
    return transpiler.transpile(ast)

  def test_subclass_of_base_transpiler(self):
    transpiler = LLVMTranspiler()
    self.assertIsInstance(transpiler, BaseTranspiler)

  def test_integer_arithmetic(self):
    code = """
    func add(a: int, b: int): int {
        return a + b;
    }
    """
    ir_out = self._parse_and_transpile(code)
    self.assertIn('define i64 @"add"', ir_out)
    self.assertIn("alloca i64", ir_out)
    self.assertIn("add i64", ir_out)
    self.assertIn("ret i64", ir_out)

  def test_float_arithmetic(self):
    code = """
    func add_float(a: float, b: float): float {
        return a + b;
    }
    """
    ir_out = self._parse_and_transpile(code)
    self.assertIn('define double @"add_float"', ir_out)
    self.assertIn("fadd double", ir_out)
    self.assertIn("ret double", ir_out)

  def test_local_var_decl_and_assignment(self):
    code = """
    func compute(x: int): int {
        var y: int = 10;
        y = y + x;
        return y;
    }
    """
    ir_out = self._parse_and_transpile(code)
    self.assertIn('define i64 @"compute"', ir_out)
    self.assertIn("alloca i64", ir_out)
    self.assertIn("store i64 10", ir_out)
    self.assertIn("add i64", ir_out)
    self.assertIn("ret i64", ir_out)

  def test_struct_declaration(self):
    code = """
    struct Player {
        var hp: int;
        var score: float;
    }
    """
    ir_out = self._parse_and_transpile(code)
    self.assertIn('%"struct.Player" = type {i64, double}', ir_out)

  def test_implicit_void_return(self):
    code = """
    func do_nothing() {
    }
    """
    ir_out = self._parse_and_transpile(code)
    self.assertIn('define void @"do_nothing"', ir_out)
    self.assertIn("ret void", ir_out)

  def test_unsupported_node_raises_not_implemented(self):
    transpiler = LLVMTranspiler()
    dummy_program = ProgramNode(declarations=[])
    res = transpiler.transpile(dummy_program)
    self.assertIn("target triple =", res)


if __name__ == "__main__":
  unittest.main()
